graph TD;
v0-->v7;
v7-->v0;
v0-->v9;
v9-->v0;
v0-->v11;
v11-->v0;
v7-->v11;
v11-->v7;
v7-->v6;
v6-->v7;
v7-->v3;
v3-->v7;
v6-->v5;
v5-->v6;
v3-->v4;
v4-->v3;
v2-->v3;
v3-->v2;
v2-->v12;
v12-->v2;
v12-->v8;
v8-->v12;
v8-->v1;
v1-->v8;
v1-->v10;
v10-->v1;
